<?php
/**
 * Infinity Features Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 *
 * This file is a work in progress.
 *
 * @package Infinity
 * @subpackage config
 */

// overlay image defaults
$overlay_image_defaults = array(
	'type' => 'css/overlay-image',
	'file_directory' => 'assets/images/textures'
);

//
// Core Group
//
ice_register_group( 'core' );

	// Global Options
	ice_register_feature(
		array(
			'name' => 'options',
			'group' => 'core',
			'type' => 'default',
			'title' => __( 'Custom CSS', 'infinity-engine' ),
			'description' => __( 'Core set of options included with Infinity Base', 'infinity-engine' )
		)
	);

		$infinity_core_options_defaults = array(
			'group' => 'core',
			'section' => 'global',
			'required_feature' => 'options'
		);

		ice_register_option(
			array(
				'name' => 'text-color',
				'type' => 'colorpicker',
				'title' => __( 'Text Color', 'infinity-engine' ),
				'description' => __( 'Choose a text color', 'infinity-engine' ),
				'style_selector' => 'body.theme-option',
				'style_property' => 'color'
			),
			$infinity_core_options_defaults
		);

		ice_register_option(
			array(
				'name' => 'link-color',
				'type' => 'colorpicker',
				'title' => __( 'Link Color', 'infinity-engine' ),
				'description' => __( 'Choose a link color', 'infinity-engine' ),
				'style_selector' => 'body.theme-option a, body.theme-option a:visited',
				'style_property' => 'color'
			),
			$infinity_core_options_defaults
		);

		ice_register_option(
			array(
				'name' => 'custom-favicon',
				'type' => 'upload',
				'title' => __( 'Site Favicon', 'infinity-engine' ),
				'description' => __( 'Upload a favicon for your site', 'infinity-engine' ),
				'default_value' => 'assets/images/favicon.png'
			),
			$infinity_core_options_defaults
		);

		ice_register_option(
			array(
				'name' => 'sidebar-position',
				'section' => 'sidebar',
				'title' => __( 'Sidebar Position', 'infinity-engine' ),
				'description' => __( 'Choose on which side you want to display the sidebar', 'infinity-engine' ),
				'type' => 'radio',
				'default_value' => 'left',
				'field_options' => array(
					'left' => 'Left',
					'right' => 'Right'
				)
			),
			$infinity_core_options_defaults
		);

		ice_register_option(
			array(
				'name' => 'sidebar-size',
				'section' => 'sidebar',
				'title' => __( 'Sidebar Size', 'infinity-engine' ),
				'description' => __( 'Select a sidebar size', 'infinity-engine' ),
				'type' => 'select',
				'default_value' => 'twelve',
				'field_options' => array(
					'fourteen' => '15 percent',
					'thirteen' => '20 percent',
					'twelve' => '25 percent',
					'eleven' => '30 precent',
					'ten' => '35 percent',
					'nine' => '40 percent',
					'eight' => '50 percent',
					'disable' => 'Disable'
				)
			),
			$infinity_core_options_defaults
		);

		ice_register_option(
			array(
				'name' => 'google-analytics',
				'type' => 'textarea',
				'title' => __( 'Google Analytics Code', 'infinity-engine' ),
				'description' => __( 'Paste your GA Tracking code in the text area below. Including the script tags!', 'infinity-engine' )
			),
			$infinity_core_options_defaults
		);

		ice_register_option(
			array(
				'name' => 'footer-text',
				'section' => 'footer',
				'type' => 'textarea',
				'title' => __( 'Footer Text', 'infinity-engine' ),
				'description' => __( 'The footer text that appears at the bottom of every page, below the widgetized footer areas. This is commonly used for copyright, designed by, and powered by text. HTML tags are allowed.', 'infinity-engine' ),
				'default_value' => __( 'Infinity by <a href=http://infinity.presscrew.com>PressCrew</a> and powered by <a href=http://wordpress.org>WordPress</a>.', 'infinity-engine' )
			),
			$infinity_core_options_defaults
		);

//
// Top Menu Group
//
ice_register_group( 'top-menu' );

	// Top Menu Setup
	ice_register_feature(
		array(
			'name' => 'setup',
			'group' => 'top-menu',
			'type' => 'default',
			'title' => __( 'Above Header Menu Setup', 'infinity-engine' ),
			'description' => __( 'Register the menu above the header.', 'infinity-engine' )
		)
	);

	// Top Menu Layout
	ice_register_feature(
		array(
			'name' => 'layout',
			'group' => 'top-menu',
			'type' => 'default',
			'title' => __( 'Sub Menu Styles', 'infinity-engine' ),
			'description' => __( 'Customize the layout and colors of the menu above the header.', 'infinity-engine' )
		)
	);

		$infinity_top_menu_defaults = array(
			'group' => 'top-menu',
			'section' => 'menus-top',
			'required_feature' => 'layout'
		);

		ice_register_option(
			array(
				'name' => 'color-link',		
				'type' => 'colorpicker',
				'title' => __( 'Font Color', 'infinity-engine' ),
				'description' => __( 'Choose a font color for links of the menu above the header.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option .top-menu ul li a span',
				'style_property' => 'color'
			),
			$infinity_top_menu_defaults
		);

		ice_register_option(
			array(
				'name' => 'font-weight',
				'type' => 'select',
				'title' => __( 'Font Weight', 'infinity-engine' ),
				'description' => __( 'Choose a font weight for links of the menu above the header.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option .top-menu ul li a span',
				'style_property' => 'font-weight'
			),
			$infinity_top_menu_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-color',
				'type' => 'css/bg-color',
				'style_selector' => 'body.theme-option .top-menu'
			),
			$infinity_top_menu_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-color-subitem',
				'type' => 'css/bg-color',
				'title' => __( 'Sub-item Background', 'infinity-engine' ),
				'description' => __( 'Choose a background color for the submenu items of the menu above the header.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option .top-menu ul ul'
			),
			$infinity_top_menu_defaults
		);

		ice_register_option(
			array(
				'name' => 'overlay-image',
				'group' => 'top-menu',
				'section' => 'menus-top',
				'style_selector' => 'body.theme-option .top-menu'
			),
			array_merge( $infinity_top_menu_defaults, $overlay_image_defaults )
		);

		ice_register_option(
			array(
				'name' => 'overlay-opacity',
				'type' => 'css/overlay-opacity',
				'style_selector' => 'body.theme-option .top-menu:before',
				'parent' => 'overlay-image',
				'linked_image' => 'overlay-image'
			),
			$infinity_top_menu_defaults
		);

//
// Main Menu Group
//
ice_register_group( 'main-menu' );

	// Main Menu Setup
	ice_register_feature(
		array(
			'name' => 'setup',
			'group' => 'main-menu',
			'type' => 'default',
			'title' => __( 'Inside Header Menu Setup', 'infinity-engine' ),
			'description' => __( 'Register the menu inside the header.', 'infinity-engine' )
		)
	);

	// Main Menu Layout
	ice_register_feature(
		array(
			'name' => 'layout',
			'group' => 'main-menu',
			'type' => 'default',
			'title' => __( 'Main Menu Styles', 'infinity-engine' ),
			'description' => __( 'Customize the layout and colors of the menu inside the header.', 'infinity-engine' )
		)
	);
	
		$infinity_main_menu_defaults = array(
			'group' => 'main-menu',
			'section' => 'menus-main',
			'required_feature' => 'layout'
		);
		
		ice_register_option(
			array(
				'name' => 'color-link',
				'type' => 'colorpicker',
				'title' => __( 'Font Color', 'infinity-engine' ),
				'description' => __( 'Choose a font color for links of the menu inside the header.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option .main-menu ul li a span',
				'style_property' => 'color'
			),
			$infinity_main_menu_defaults
		);

		ice_register_option(
			array(
				'name' => 'font-weight',
				'type' => 'select',
				'title' => __( 'Font Weight', 'infinity-engine' ),
				'description' => __( 'Choose a font weight for links of the menu inside the header.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option .main-menu ul li a span',
				'style_property' => 'font-weight'
			),
			$infinity_main_menu_defaults
		);

		ice_register_option(
			array(
				'name' => 'padding',
				'type' => 'css/length-px',
				'title' => __( 'Padding', 'infinity-engine' ),
				'description' => __( 'Select the padding (spacing) around the menu links by moving the slider.', 'infinity-engine' ),
				'max' => 30,
				'style_selector' => 'body.theme-option .main-menu',
				'style_property' => 'padding'
			),
			$infinity_main_menu_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-color',
				'type' => 'css/bg-color',
				'style_selector' => 'body.theme-option .main-menu'
			),
			$infinity_main_menu_defaults
		);

		ice_register_option(
			array(
				'name' => 'overlay-image',
				'style_selector' => 'body.theme-option .main-menu'
			),
			array_merge( $infinity_main_menu_defaults, $overlay_image_defaults )
		);

		ice_register_option(
			array(
				'name' => 'overlay-opacity',
				'type' => 'css/overlay-opacity',
				'style_selector' => 'body.theme-option .main-menu:before',
				'parent' => 'overlay-image',
				'linked_image' => 'overlay-image'
			),
			$infinity_main_menu_defaults
		);

//
// Sub Menu Group
//
ice_register_group( 'sub-menu' );

	// Sub Menu Setup
	ice_register_feature(
		array(
			'name' => 'setup',
			'group' => 'sub-menu',
			'type' => 'default',
			'title' => __( 'Below Header Menu Setup', 'infinity-engine' ),
			'description' => __( 'Register the menu below the header.', 'infinity-engine' )
		)
	);

	// Sub Menu Layout
	ice_register_feature(
		array(
			'name' => 'layout',
			'group' => 'sub-menu',
			'type' => 'default',
			'title' => __( 'Sub Menu Styles', 'infinity-engine' ),
			'description' => __( 'Customize the layout and colors of the menu below the header.', 'infinity-engine' )
		)
	);
	
		$infinity_sub_menu_defaults = array(
			'group' => 'sub-menu',
			'section' => 'menus-sub',
			'required_feature' => 'layout'
		);
		
		ice_register_option(
			array(
				'name' => 'color-link',
				'type' => 'colorpicker',
				'title' => __( 'Font Color', 'infinity-engine' ),
				'description' => __( 'Choose a font color for links of the menu below the header.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option .sub-menu ul li a span',
				'style_property' => 'color'
			),
			$infinity_sub_menu_defaults
		);

		ice_register_option(
			array(
				'name' => 'font-weight',
				'type' => 'select',
				'title' => __( 'Font Weight', 'infinity-engine' ),
				'description' => __( 'Choose a font weight for links of the menu below the header.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option .sub-menu ul li a span',
				'style_property' => 'font-weight'
			),
			$infinity_sub_menu_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-color',
				'type' => 'css/bg-color',
				'style_selector' => 'body.theme-option .sub-menu'
			),
			$infinity_sub_menu_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-color-subitem',
				'type' => 'css/bg-color',
				'title' => __( 'Sub-item Background', 'infinity-engine' ),
				'description' => __( 'Choose a background color for the submenu items of the menu below the header.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option .sub-menu ul ul'
			),
			$infinity_sub_menu_defaults
		);

		ice_register_option(
			array(
				'name' => 'overlay-image',
				'style_selector' => 'body.theme-option .sub-menu'
			),
			array_merge( $infinity_sub_menu_defaults, $overlay_image_defaults )
		);

		ice_register_option(
			array(
				'name' => 'overlay-opacity',
				'type' => 'css/overlay-opacity',
				'style_selector' => 'body.theme-option .sub-menu:before',
				'parent' => 'overlay-image',
				'linked_image' => 'overlay-image'
			),
			$infinity_sub_menu_defaults
		);

//
// Footer Menu Group
//
ice_register_group( 'footer-menu' );

	// Footer Menu Setup
	ice_register_feature(
		array(
			'name' => 'setup',
			'group' => 'footer-menu',
			'type' => 'default',
			'title' => __( 'Footer Menu Setup', 'infinity-engine' ),
			'description' => __( 'Register the footer menu.', 'infinity-engine' )
		)
	);


//
// Sidebar Group
//
ice_register_group( 'sidebar' );

	// Sidebar Setup
	ice_register_feature(
		array(
			'name' => 'setup',
			'group' => 'sidebar',
			'type' => 'default',
			'title' => __( 'Sidebar Setup', 'infinity-engine' ),
			'description' => __( 'Sidebar Registration', 'infinity-engine' )
		)
	);

	// Sidebar Layout
	ice_register_feature(
		array(
			'name' => 'layout',
			'group' => 'sidebar',
			'type' => 'default',
			'title' => __( 'sidebar Styles', 'infinity-engine' ),
			'description' => __( 'Customize the layout and colors of the sidebar', 'infinity-engine' )
		)
	);

		$infinity_sidebar_layout_defaults = array(
			'group' => 'sidebar',
			'section' => 'sidebar',
			'required_feature' => 'layout',
			'style_selector' => 'body.theme-option #sidebar'
		);

		ice_register_option(
			array(
				'name' => 'text-color',
				'type' => 'colorpicker',
				'title' => __( 'Text Color', 'infinity-engine' ),
				'description' => __( 'Choose a color for text in the sidebar.', 'infinity-engine' ),
				'style_property' => 'color'
			),
			$infinity_sidebar_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'link-color',
				'type' => 'colorpicker',
				'title' => __( 'Link Color', 'infinity-engine' ),
				'description' => __( 'Choose a color for links in the sidebar.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option #sidebar a',
				'style_property' => 'color'
			),
			$infinity_sidebar_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-color',
				'type' => 'css/bg-color',
			),
			$infinity_sidebar_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-image',
				'type' => 'css/bg-image',
			),
			$infinity_sidebar_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-repeat',
				'type' => 'css/bg-repeat',
				'parent' => 'background-image',
			),
			$infinity_sidebar_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'overlay-image',
			),
			array_merge( $infinity_sidebar_layout_defaults, $overlay_image_defaults )
		);

		ice_register_option(
			array(
				'name' => 'overlay-opacity',
				'type' => 'css/overlay-opacity',
				'style_selector' => 'body.theme-option #sidebar:before',
				'parent' => 'overlay-image',
				'linked_image' => 'overlay-image'
			),
			$infinity_sidebar_layout_defaults
		);

//
// Post Group
//
ice_register_group( 'post' );

	// Post Pagination
	ice_register_feature(
		array(
			'name' => 'pagination',
			'group' => 'post',
			'type' => 'default',
			'title' => __( 'Pagination', 'infinity-engine' ),
			'description' => __( 'Enable pagination for your (custom) posts', 'infinity-engine' )
		)
	);

	// Introduction boxes
	ice_register_feature(
		array(
			'name' => 'intro-boxes',
			'group' => 'post',
			'type' => 'default',
			'title' => __( 'Introduction Boxes', 'infinity-engine' ),
			'description' => __( 'Introduction boxes that show above category, tag and author archives', 'infinity-engine' )
		)
	);

	// Author Boxes
	ice_register_feature(
		array(
			'name' => 'author-boxes',
			'group' => 'post',
			'type' => 'default',
			'title' => __( 'Author Boxes', 'infinity-engine' ),
			'description' => __( 'Enable About the Author Boxes being displayed on single posts and author archives', 'infinity-engine' )
		)
	);

	// Post Avatars
	ice_register_feature(
		array(
			'name' => 'avatars',
			'group' => 'post',
			'type' => 'default',
			'title' => __( 'Post Avatars', 'infinity-engine' ),
			'description' => __( 'Enable Post avatars being displayed on single posts and pages', 'infinity-engine' )
		)
	);

//
// Post Gravatars Group
//
ice_register_group( 'post-gravatar' );

	// Post Gravatars
	ice_register_feature(
		array(
			'name' => 'post-gravatar',
			'group' => 'post-gravatar',
			'type' => 'gravatar',
			'title' => __( 'Post Gravatars', 'infinity-engine' ),
			'description' => __( 'Total control over post gravatars', 'infinity-engine' ),
			'image_class' => 'infinity-post-gravatar'
		)
	);

		$infinity_post_grav_defaults = array(
			'group' => 'post-gravatar',
			'section' => 'gravatars',
			'required_feature' => 'gravatar'
		);

		ice_register_option(
			array(
				'name' => 'size',
				'type' => 'text',
				'title' => __( 'Size', 'infinity-engine' ),
				'description' => __( 'Enter the size in pixels for the Gravatar image', 'infinity-engine' )
			),
			$infinity_post_grav_defaults
		);

		ice_register_option(
			array(
				'name' => 'default-set',
				'type' => 'select',
				'title' => __( 'Default Image Set', 'infinity-engine' ),
				'description' => __( 'Select the default image set to use', 'infinity-engine' ),
				'default_value' => 'mm',
				'field_options' => array(
					'404' => 'Return 404 Error',
					'mm' => 'Mystery Man',
					'identicon' => 'Identicon',
					'monsterid' => 'Monster ID',
					'wavatar' => 'Wavatar',
					'retro' => 'Retro'
				)
			),
			$infinity_post_grav_defaults
		);

		ice_register_option(
			array(
				'name' => 'default-img',
				'type' => 'upload',
				'title' => __( 'Default Image File', 'infinity-engine' ),
				'description' => __( 'Upload a default Gravatar image (overrides default set)', 'infinity-engine' )
			),
			$infinity_post_grav_defaults
		);

		ice_register_option(
			array(
				'name' => 'default-force',
				'type' => 'toggle/yes-no',
				'title' => __( 'Force Default', 'infinity-engine' ),
				'description' => __( 'Force default image to always load?', 'infinity-engine' ),
				'default_value' => false
			),
			$infinity_post_grav_defaults
		);

		ice_register_option(
			array(
				'name' => 'rating',
				'type' => 'select',
				'title' => __( 'Rating', 'infinity-engine' ),
				'description' => __( 'Select highest image rating to display', 'infinity-engine' ),
				'default_value' => 'g',
				'field_options' => array(
					'g' => 'G (suitable for display on all websites with any audience type)',
					'pg' => 'PG (may contain rude gestures, provocatively dressed individuals, the lesser swear words, or mild violence)',
					'r' => 'R (may contain such things as harsh profanity, intense violence, nudity, or hard drug use)',
					'x' => 'X (may contain hardcore sexual imagery or extremely disturbing violence)'
				)
			),
			$infinity_post_grav_defaults
		);

		ice_register_option(
			array(
				'name' => 'border-width',
				'type' => 'text',
				'title' => __( 'Border Width', 'infinity-engine' ),
				'description' => __( 'Enter a border width in pixels for the Gravatar image', 'infinity-engine' )
			),
			$infinity_post_grav_defaults
		);

		ice_register_option(
			array(
				'name' => 'border-color',
				'type' => 'colorpicker',
				'title' => __( 'Border Color', 'infinity-engine' ),
				'description' => __( 'Select a color for the Gravatar image border', 'infinity-engine' )
			),
			$infinity_post_grav_defaults
		);

		ice_register_option(
			array(
				'name' => 'padding',
				'type' => 'text',
				'title' => __( 'Padding', 'infinity-engine' ),
				'description' => __( 'Enter a padding size in pixels for the Gravatar image', 'infinity-engine' )
			),
			$infinity_post_grav_defaults
		);

		ice_register_option(
			array(
				'name' => 'bg-color',
				'type' => 'colorpicker',
				'title' => __( 'Background Color', 'infinity-engine' ),
				'description' => __( 'Select a background color for the Gravatar image', 'infinity-engine' )
			),
			$infinity_post_grav_defaults
		);

//
// Font Group
//
ice_register_group( 'font' );

	// Icon Sweets
	ice_register_feature(
		array(
			'name' => 'iconsweets',
			'group' => 'font',
			'type' => 'default',
			'title' => __( 'The Icon Font-Face being used', 'infinity-engine' ),
			'description' => __( 'Icons', 'infinity-engine' ),
			'style' => 'assets/fonts/iconsweets.css'
		)
	);

//
// WP Group
//
ice_register_group( 'wp' );

	// WordPress Support
	ice_register_feature(
		array(
			'name' => 'support',
			'group' => 'wp',
			'type' => 'default',
			'title' => __( 'Wordpress Support', 'infinity-engine' ),
			'description' => __( 'Enables WordPress support', 'infinity-engine' ),
			'style' => 'assets/css/wordpress.css'
		)
	);
	
	// Base WordPress Styles
	ice_register_feature(
		array(
			'name' => 'style',
			'group' => 'wp',
			'type' => 'default',
			'title' => __( 'WordPress Styles', 'infinity-engine' ),
			'description' => __( 'The base WordPress styling', 'infinity-engine' ),
			'body_class' => 'infinity-wp'
		)
	);

//
// BP Group
//
ice_register_group( 'bp' );

	// BuddyPress support
	ice_register_feature(
		array(
			'name' => 'support',
			'group' => 'bp',
			'type' => 'bp/support',
			'title' => __( 'BuddyPress Support', 'infinity-engine' ),
			'description' => __( 'Enables BuddyPress support', 'infinity-engine' )
		)
	);

	// Base BuddyPress Styles
	ice_register_feature(
		array(
			'name' => 'style',
			'group' => 'bp',
			'type' => 'default',
			'title' => __( 'BuddyPress Styles', 'infinity-engine' ),
			'description' => __( 'The base BuddyPress styles', 'infinity-engine' ),
			'body_class' => 'infinity-bp',
			'style' => 'assets/css/plugins/buddypress.css'
		)
	);

	// BP Sidebar Setup
	ice_register_feature(
		array(
			'name' => 'sidebar-setup',
			'group' => 'bp',
			'section' => 'buddypress',
			'type' => 'default',
			'title' => __( 'BuddyPress Sidebar', 'infinity-engine' ),
			'description' => __( 'Special BuddyPress sidebar registration', 'infinity-engine' ),
			'required_feature' => 'support'
		)
	);

//
// Plugins Compat Group
//
ice_register_group( 'plugins' );

	// All other plugin styles
	ice_register_feature(
		array(
			'name' => 'other',
			'group' => 'plugins',
			'type' => 'default',
			'title' => __( 'Other Plugins Styles', 'infinity-engine' ),
			'description' => __( 'Other plugins support styles', 'infinity-engine' ),
			'style' => 'assets/css/plugins/other.css'
		)
	);

//
// BP FBConnect Group
//
ice_register_group( 'bp-fbconnect' );

	// BP Facebook Connect Support
	ice_register_feature(
		array(
			'name' => 'support',
			'group' => 'bp-fbconnect',
			'type' => 'bp/fb-autoconnect',
			'class' => 'info-box register-intro'
		)
	);
		ice_register_option(
			array(
				'name' => 'toggle',
				'group' => 'bp-fbconnect',
				'section' => 'buddypress',
				'type' => 'toggle/yes-no',
				'required_feature' => 'support',
				'title' => __( 'FaceBook Connect', 'infinity-engine' ),
				'description' => __( 'Show connect with Facebook button?', 'infinity-engine' ),
				'default_value' => true
			)
		);

//
// BP Protect Group
//
ice_register_group( 'bp-protect' );

	// BP Protect Support
	ice_register_feature(
		array(
			'name' => 'support',
			'group' => 'bp-protect',
			'type' => 'bp/protect'
		)
	);
		ice_register_option(
			array(
				'name' => 'toggle',
				'group' => 'bp-protect',
				'section' => 'buddypress',
				'type' => 'toggle/on-off',
				'required_feature' => 'support',
				'title' => __( 'Private Community', 'infinity-engine' ),
				'description' => __( 'Turn this option on to restrict access to your BuddyPress components to members only.', 'infinity-engine' ),
				'default_value' => false
			)
		);

//
// BP Tour Group
//
ice_register_group( 'bp-tour' );

	// BP Protect Support
	ice_register_feature(
		array(
			'name' => 'activity',
			'group' => 'bp-tour',
			'type' => 'bp/tour',
			'cookie_name' => 'buddypress-tour'
		)
	);
		$infinity_bp_tour_defaults = array(
			'group' => 'bp-tour',
			'type' => 'textarea',
			'section' => 'buddypress',
			'field_class' => 'css-editor'
		);

		ice_register_option(
			array(
				'name' => 'start',
				'title' => __( 'Activity Stream Tour', 'infinity-engine' ),
				'description' => __( 'The first text that is being displayed before the tour starts.', 'infinity-engine' ),
				'default_value' => __( "<h4>Hi there!</h4> It seems that this is the first time you've visited our Activity Stream, so let's give you a quick tour of our Features! Ready? Let's do this!", 'infinity-engine' )
			),
			$infinity_bp_tour_defaults
		);

		ice_register_option(
			array(
				'name' => 'all',
				'title' => __( 'All Members Text', 'infinity-engine' ),
				'description' => __( 'The text explaining the All Members button.', 'infinity-engine' ),
				'default_value' => __( "<h4>All Members</h4> If you like to get a nice overview of <em>all the activity</em> posted by our community, this is the button to click!", 'infinity-engine' )
			),
			$infinity_bp_tour_defaults
		);

		ice_register_option(
			array(
				'name' => 'friends',
				'title' => __( 'Friends Text', 'infinity-engine' ),
				'description' => __( 'The text explaining the Friends button.', 'infinity-engine' ),
				'default_value' => __( "<h4>My Friends</h4> Keep track of what your friends are doing. No buddies yet? Why don't you make some by visting the Members Directory!</a>", 'infinity-engine' )
			),
			$infinity_bp_tour_defaults
		);

		ice_register_option(
			array(
				'name' => 'groups',
				'title' => __( 'Groups Text', 'infinity-engine' ),
				'description' => __( 'The text explaining the Groups button.', 'infinity-engine' ),
				'default_value' => __( "<h4>My Groups</h4> By clicking the &quot;My Groups&quot; button you can keep track of what's happening in the groups you've joined. Not a member of a group yet? Check out the Groups Directory!</a>", 'infinity-engine' )
			),
			$infinity_bp_tour_defaults
		);

		ice_register_option(
			array(
				'name' => 'mentions',
				'title' => __( 'Mentions Text', 'infinity-engine' ),
				'description' => __( 'The text explaining the Mentions button.', 'infinity-engine' ),
				'default_value' => __( "<h4>Mentions</h4> You can easily &quot;Mention&quot; others in your updates or forum posts across our community. As soon as someone mentions you using @yourname you'll see these mentions appear under this button.", 'infinity-engine' )
			),
			$infinity_bp_tour_defaults
		);

		ice_register_option(
			array(
				'name' => 'favorites',
				'title' => __( 'Favorites Text', 'infinity-engine' ),
				'description' => __( 'The text explaining the Favorites button.', 'infinity-engine' ),
				'default_value' => __( "<h4>Keep Track</h4> If there's a conversation brewing that you find interesting, you can add your voice by clicking on the <strong>Comment</strong> button. By using the <strong>Favorite</strong> button you can easily bookmark the conversation so you go back to it back later. Go ahead and <strong>try it</strong> by clicking on a &quot;Favorite&quot; button!", 'infinity-engine' )
			),
			$infinity_bp_tour_defaults
		);

		ice_register_option(
			array(
				'name' => 'filter',
				'title' => __( 'Filter Text', 'infinity-engine' ),
				'description' => __( 'The text explaining the filter dropdown.', 'infinity-engine' ),
				'default_value' => __( "<h4>Use the filter!</h4> You can filter the stream to only show the items that have caught your interest. For instance you could use the filter <strong>Posts</strong> to show blog posts from across our network. Awesome!", 'infinity-engine' )
			),
			$infinity_bp_tour_defaults
		);

		ice_register_option(
			array(
				'name' => 'update',
				'title' => __( 'Update Text', 'infinity-engine' ),
				'description' => __( 'The last text in the tour prompting your user to post an update.', 'infinity-engine' ),
				'default_value' => __( "<h4>Update Away!</h4> We have taught you everything you need to know to get started! It's time for you to post your first update. Good luck young grasshopper, we've taught you well!", 'infinity-engine' )
			),
			$infinity_bp_tour_defaults
		);

//
// Extensions Group
//
ice_register_group( 'ext' );

	// Extensions Support
	ice_register_feature(
		array(
			'name' => 'support',
			'group' => 'ext',
			'type' => 'default',
			'title' => __( 'Extension Styles', 'infinity-engine' ),
			'description' => __( 'Enables extensions support', 'infinity-engine' ),
			'style' => 'assets/css/extensions.css'
		)
	);

//
// Responsive Group
//
ice_register_group( 'resp' );

	// Responsive Layout Support
	ice_register_feature(
		array(
			'name' => 'support',
			'group' => 'resp',
			'type' => 'responsive/layout',
			'title' => __( 'Responsive Layout', 'infinity-engine' ),
			'description' => __( 'Enables responsive layout support', 'infinity-engine' ),
			'style' => 'assets/css/responsive.css'
		)
	);

	// Responsive Menus
	ice_register_feature(
		array(
			'name' => 'menu',
			'group' => 'resp',
			'type' => 'responsive/menu',
			'title' => __( 'Responsive Menu', 'infinity-engine' ),
			'description' => __( 'Enables the responsive menu javascript', 'infinity-engine' ),
			'target_selector' => '.sf-menu',
			'switch_width' => 770,
			'top_option_text' => 'Where to?',
			'prepend_to' => 'div.mobile-menu-container'
		)
	);

	// Responsive Videos
	ice_register_feature(
		array(
			'name' => 'videos',
			'group' => 'resp',
			'type' => 'responsive/videos',
			'title' => __( 'Responsive Videos', 'infinity-engine' ),
			'description' => __( 'Enables the responsive videos javascript', 'infinity-engine' ),
			'target_selector' => '#wrapper'
		)
	);

//
// Typography Group
//
ice_register_group( 'typog' );

	// Typography Styles
	ice_register_feature(
		array(
			'name' => 'style',
			'group' => 'typog',
			'type' => 'default',
			'title' => __( 'Typography Styles', 'infinity-engine' ),
			'description' => __( 'The base Typography styling', 'infinity-engine' ),
			'body_class' => 'infinity-typog'
		)
	);

//
// Layout Group
//
ice_register_group( 'layout' );

	// Layout Styles
	ice_register_feature(
		array(
			'name' => 'style',
			'group' => 'layout',
			'type' => 'default',
			'title' => __( 'Layout Styles', 'infinity-engine' ),
			'description' => __( 'The base layout styling', 'infinity-engine' ),
			'body_class' => 'infinity-layout'
		)
	);

//
// Buttons Group
//
ice_register_group( 'buttons' );

	// Button Styles
	ice_register_feature(
		array(
			'name' => 'style',
			'group' => 'buttons',
			'type' => 'default',
			'title' => __( 'extras Styles', 'infinity-engine' ),
			'description' => __( 'The base buttons styling', 'infinity-engine' ),
			'body_class' => 'infinity-btns'
		)
	);

	// Button Colors
	ice_register_feature(
		array(
			'name' => 'color',
			'group' => 'buttons',
			'type' => 'default',
			'title' => __( 'Custom button colors', 'infinity-engine' ),
			'description' => __( 'Custom button colors.', 'infinity-engine' ),
			'body_class' => 'infinity-btns'
		)
	);

		ice_register_option(
			array(
				'name' => 'custom-color',
				'group' => 'buttons',
				'section' => 'global',
				'type' => 'select',
				'title' => __( 'Button Color', 'infinity-engine' ),
				'description' => __( 'Choose a button color.', 'infinity-engine' ),
				'field_options' => array(
					'orange' => 'Orange',
					'blue' => 'Blue',
					'darkblue' => 'Navy Blue',
					'black' => 'Black',
					'purple' => 'Purple',
					'grey' => 'Grey',
					'teal' => 'Teal',
					'purple' => 'Purple',
					'green' => 'Green',
					'pink' => 'Pink',
					'white' => 'White'
				),
				'default_value' => 'orange'
			)
		);

//
// Icons Group
//
ice_register_group( 'icons' );

	// Icon Styles
	ice_register_feature(
		array(
			'name' => 'style',
			'group' => 'icons',
			'type' => 'default',
			'title' => __( 'The Icons used across the theme', 'infinity-engine' ),
			'description' => __( 'Icons', 'infinity-engine' ),
			'body_class' => 'infinity-icons'
		)
	);

//
// Design Group
//
ice_register_group( 'design' );

	// Design Styles
	ice_register_feature(
		array(
			'name' => 'style',
			'group' => 'design',
			'type' => 'default',
			'title' => __( 'Design Styles', 'infinity-engine' ),
			'description' => __( 'The styles which fancy things up a bit', 'infinity-engine' ),
			'body_class' => 'infinity-design'
		)
	);

//
// Base Group
//
ice_register_group( 'base' );

	// Base Scripts
	ice_register_feature(
		array(
			'name' => 'script',
			'group' => 'base',
			'type' => 'default',
			'title' => __( 'Base Javascript', 'infinity-engine' ),
			'description' => __( 'Some jQuery to spice up the Base Theme', 'infinity-engine' ),
			'script' => 'assets/js/base.js',
			'script_depends' => array(
				'jquery'
			)
		)
	);

//
// Custom Group
//
ice_register_group( 'custom' );

	// Custom CSS
	ice_register_feature(
		array(
			'name' => 'css',
			'group' => 'custom',
			'type' => 'default',
			'title' => __( 'Custom CSS', 'infinity-engine' ),
			'description' => __( 'Allow custom CSS to be provided with theme options', 'infinity-engine' )
		)
	);
		ice_register_option(
			array(
				'name' => 'markup',
				'group' => 'custom',
				'section' => 'global',
				'type' => 'css/custom',
				'title' => __( 'Custom CSS', 'infinity-engine' ),
				'description' => __( 'Enter custom CSS markup to fine tune the look of your site', 'infinity-engine' )
			)
		);

//
// Body Group
//
ice_register_group( 'body' );

	// Body Layout
	ice_register_feature(
		array(
			'name' => 'layout',
			'group' => 'body',
			'type' => 'default',
			'title' => __( 'Body Layout', 'infinity-engine' ),
			'description' => __( 'Change the Body according to your taste', 'infinity-engine' )
		)
	);

		$infinity_body_layout_defaults = array(
			'group' => 'body',
			'section' => 'layout',
			'required_feature' => 'layout',
			'style_selector' => 'body.theme-option'
		);

		ice_register_option(
			array(
				'name' => 'width',
				'type' => 'css/length-px',
				'title' => __( 'Maximum Width', 'infinity-engine' ),
				'description' => __( 'Set the maximum width of the site\'s content between %min% and %max% pixels by moving the slider.', 'infinity-engine' ),
				'min' => 900,
				'max' => 1250,
				'step' => 10,
				'style_selector' => 'body.theme-option #wrapper',
				'style_property' => 'max-width'
			),
			$infinity_body_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-color',
				'type' => 'css/bg-color'
			),
			$infinity_body_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-image',
				'type' => 'css/bg-image',
				'default_value' => 'assets/images/design/bg-body.gif'
			),
			$infinity_body_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-repeat',
				'type' => 'css/bg-repeat',
				'parent' => 'background-image'
			),
			$infinity_body_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'overlay-image',
			),
			array_merge( $infinity_body_layout_defaults, $overlay_image_defaults )
		);

		ice_register_option(
			array(
				'name' => 'overlay-opacity',
				'type' => 'css/overlay-opacity',
				'style_selector' => 'body.theme-option:before',
				'parent' => 'overlay-image',
				'linked_image' => 'overlay-image'
			),
			$infinity_body_layout_defaults
		);

//
// Header Group
//
ice_register_group( 'header' );

	// Header Layout
	ice_register_feature(
		array(
			'name' => 'layout',
			'group' => 'header',
			'type' => 'default',
			'title' => __( 'Header Styles', 'infinity-engine' ),
			'description' => __( 'Customize the layout and colors of the header', 'infinity-engine' )
		)
	);

		$infinity_header_layout_defaults = array(
			'group' => 'header',
			'section' => 'header',
			'required_feature' => 'layout',
			'style_selector' => 'body.theme-option #header'
		);

		ice_register_option(
			array(
				'name' => 'min-height',
				'type' => 'css/length-px',
				'title' => __( 'Height', 'infinity-engine' ),
				'description' => __( 'Select the height of the header by moving the slider', 'infinity-engine' ),
				'min' => 100,
				'max' => 500,
				'step' => 10,
				'style_property' => 'height'
			),
			$infinity_header_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'margin-top',
				'type' => 'css/length-px',
				'title' => __( 'Top Margin', 'infinity-engine' ),
				'description' => __( 'The margin (spacing) between the top of the header and the top of the page.', 'infinity-engine' ),
				'min' => 0,
				'max' => 100,
				'step' => 2,
				'style_property' => 'margin-top'
			),
			$infinity_header_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'padding-top',
				'type' => 'css/length-px',
				'title' => __( 'Top Padding', 'infinity-engine' ),
				'description' => __( 'The padding (spacing) between the top of the header and the header content.', 'infinity-engine' ),
				'min' => 0,
				'max' => 100,
				'step' => 2,
				'style_property' => 'padding-top'
			),
			$infinity_header_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'margin-bottom',
				'type' => 'css/length-px',
				'title' => __( 'Bottom Margin', 'infinity-engine' ),
				'description' => __( 'The margin (spacing) between the bottom of the header and the top of the content section.', 'infinity-engine' ),
				'min' => 0,
				'max' => 100,
				'step' => 2,
				'style_property' => 'margin-bottom'
			),
			$infinity_header_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'padding-bottom',
				'type' => 'css/length-px',
				'title' => __( 'Bottom Padding', 'infinity-engine' ),
				'description' => __( 'The padding (spacing) between the bottom of the header and the header content.', 'infinity-engine' ),
				'min' => 0,
				'max' => 100,
				'step' => 2,
				'style_property' => 'padding-bottom'
			),
			$infinity_header_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-color',
				'type' => 'css/bg-color'
			),
			$infinity_header_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-image',
				'type' => 'css/bg-image'
			),
			$infinity_header_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-repeat',
				'type' => 'css/bg-repeat',
				'parent' => 'background-image'
			),
			$infinity_header_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'overlay-image'
			),
			array_merge( $infinity_header_layout_defaults, $overlay_image_defaults )
		);

		ice_register_option(
			array(
				'name' => 'overlay-opacity',
				'type' => 'css/overlay-opacity',
				'style_selector' => 'body.theme-option #header:before',
				'parent' => 'overlay-image',
				'linked_image' => 'overlay-image'
			),
			$infinity_header_layout_defaults
		);

//
// Header Logo Group
//
ice_register_group( 'header-logo' );

	// Header Logo
	ice_register_feature(
		array(
			'name' => 'support',
			'group' => 'header-logo',
			'type' => 'header-logo'
		)
	);

		$infinity_header_logo_defaults = array(
			'group' => 'header-logo',
			'section' => 'header',
			'required_feature' => 'support'
		);

		ice_register_option(
			 array(
				'name' => 'image',
				'type' => 'upload',
				'title' => __( 'Logo Image', 'infinity-engine' ),
				'description' => __( 'Upload a custom logo to appear in the header', 'infinity-engine' )
			),
			$infinity_header_logo_defaults
		);

		ice_register_option(
			array(
				'name' => 'toggle',
				'type' => 'toggle/on-off',
				'title' => __( 'Logo Image On/Off', 'infinity-engine' ),
				'description' => __( 'Turn this Off to prevent any image logo from displaying, even the default.', 'infinity-engine' ),
				'default_value' => true,
				'parent' => 'image'
			),
			$infinity_header_logo_defaults
		);

		ice_register_option(
			array(
				'name' => 'pos',
				'type' => 'position/left-center-right',
				'title' => __( 'Logo Position', 'infinity-engine' ),
				'description' => __( 'Select a position for the logo', 'infinity-engine' ),
				'default_value' => 'l',
				'parent' => 'image',
			),
			$infinity_header_logo_defaults
		);

		ice_register_option(
			array(
				'name' => 'top',
				'type' => 'ui/slider',
				'title' => __( 'Logo Top Spacing', 'infinity-engine' ),
				'description' => __( 'Enter a height in pixels for top spacing', 'infinity-engine' ),
				'min' => 0,
				'max' => 100,
				'step' => 1,
				'suffix' => ' pixels',
				'style_selector' => '.icext-feature.icext-header-logo a',
				'style_property' => 'margin-top',
				'style_unit' => 'px',
				'parent' => 'image',
			),
			$infinity_header_logo_defaults
		);

		ice_register_option(
			array(
				'name' => 'left',
				'type' => 'ui/slider',
				'title' => __( 'Logo Left Spacing', 'infinity-engine' ),
				'description' => __( 'Enter a width in pixels for left spacing', 'infinity-engine' ),
				'min' => 0,
				'max' => 250,
				'step' => 1,
				'suffix' => ' pixels',
				'style_selector' => '.icext-feature.icext-header-logo a',
				'style_property' => 'margin-left',
				'style_unit' => 'px',
				'parent' => 'image',
			),
			$infinity_header_logo_defaults
		);

		ice_register_option(
			array(
				'name' => 'right',
				'type' => 'ui/slider',
				'title' => __( 'Logo Right Spacing', 'infinity-engine' ),
				'description' => __( 'Enter a width in pixels for right spacing', 'infinity-engine' ),
				'min' => 0,
				'max' => 250,
				'step' => 1,
				'suffix' => ' pixels',
				'style_selector' => '.icext-feature.icext-header-logo a',
				'style_property' => 'margin-right',
				'style_unit' => 'px',
				'parent' => 'image',
			),
			$infinity_header_logo_defaults
		);

//
// Content Group
//
ice_register_group( 'content' );

	// Content Styles
	ice_register_feature(
		array(
			'name' => 'layout',
			'group' => 'content',
			'type' => 'default',
			'title' => __( 'Content Styles', 'infinity-engine' ),
			'description' => __( 'Customize the layout and colors of the content section.', 'infinity-engine' )
		)
	);

		$infinity_content_layout_defaults = array(
			'group' => 'content',
			'section' => 'content',
			'required_feature' => 'layout',
			'style_selector' => 'body.theme-option #content'
		);

		ice_register_option(
			array(
				'name' => 'text-color',
				'type' => 'colorpicker',
				'title' => __( 'Text Color', 'infinity-engine' ),
				'description' => __( 'Choose a color for text inside the content section.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option #content a',
				'style_property' => 'color'
			),
			$infinity_content_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'link-color',
				'type' => 'colorpicker',
				'title' => __( 'Link Color', 'infinity-engine' ),
				'description' => __( 'Choose a color for links inside the content section.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option #content a',
				'style_property' => 'color'
			),
			$infinity_content_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-color',
				'type' => 'css/bg-color'
			),
			$infinity_content_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-image',
				'type' => 'css/bg-image'
			),
			$infinity_content_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-repeat',
				'type' => 'css/bg-repeat',
				'parent' => 'background-image'
			),
			$infinity_content_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'overlay-image',
				'group' => 'content',
				'section' => 'content'
			),
			array_merge( $infinity_content_layout_defaults, $overlay_image_defaults )
		);

		ice_register_option(
			array(
				'name' => 'overlay-opacity',
				'type' => 'css/overlay-opacity',
				'style_selector' => 'body.theme-option #content:before',
				'parent' => 'overlay-image',
				'linked_image' => 'overlay-image'
			),
			$infinity_content_layout_defaults
		);

//
// Widget Group
//
ice_register_group( 'widget' );

	// Widget Layout
	ice_register_feature(
		array(
			'name' => 'layout',
			'group' => 'widget',
			'type' => 'default',
			'title' => __( 'Widget Styling', 'infinity-engine' ),
			'description' => __( 'Customize the layout and colors of widgets.', 'infinity-engine' )
		)
	);

		$infinity_widget_layout_defaults = array(
			'group' => 'widget',
			'section' => 'widgets',
			'required_feature' => 'layout',
			'style_selector' => 'body.theme-option #sidebar .widget'
		);

		ice_register_option(
			array(
				'name' => 'color-link',
				'type' => 'colorpicker',
				'title' => __( 'Widget Title Color', 'infinity-engine' ),
				'description' => __( 'Choose a font color for widget titles.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option #sidebar .widget h4',
				'style_property' => 'color'
			),
			$infinity_widget_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'font-weight',
				'type' => 'select',
				'title' => __( 'Font Weight', 'infinity-engine' ),
				'description' => __( 'Choose a font weight for widget titles.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option #sidebar .widget h4',
				'style_property' => 'font-weight'
			),
			$infinity_widget_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'padding',
				'type' => 'css/length-px',
				'title' => __( 'Padding', 'infinity-engine' ),
				'description' => __( 'The padding (spacing) between any widget border and it\'s content.', 'infinity-engine' ),
				'max' => 30,
				'style_property' => 'padding'
			),
			$infinity_widget_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-color',
				'type' => 'css/bg-color',
			),
			$infinity_widget_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'overlay-image'
			),
			array_merge( $infinity_widget_layout_defaults, $overlay_image_defaults )
		);

		ice_register_option(
			array(
				'name' => 'overlay-opacity',
				'type' => 'css/overlay-opacity',
				'style_selector' => 'body.theme-option #sidebar .widget:before',
				'parent' => 'overlay-image',
				'linked_image' => 'overlay-image'
			),
			$infinity_widget_layout_defaults
		);

//
// Footer Group
//
ice_register_group( 'footer' );

	// Footer Layout
	ice_register_feature(
		array(
			'name' => 'layout',
			'group' => 'footer',
			'type' => 'default',
			'title' => __( 'footer Styles', 'infinity-engine' ),
			'description' => __( 'Customize the layout and colors of the footer', 'infinity-engine' )
		)
	);

		$infinity_footer_layout_defaults = array(
			'group' => 'footer',
			'section' => 'footer',
			'required_feature' => 'layout',
			'style_selector' => 'body.theme-option .footer-wrap'
		);

		ice_register_option(
			array(
				'name' => 'text-color',
				'type' => 'colorpicker',
				'title' => __( 'Text Color', 'infinity-engine' ),
				'description' => __( 'Choose a color for text inside the footer section.', 'infinity-engine' ),
				'style_property' => 'color'
			),
			$infinity_footer_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'text-color',
				'type' => 'colorpicker',
				'title' => __( 'Text Color', 'infinity-engine' ),
				'description' => __( 'Choose a color for text inside the footer section.', 'infinity-engine' ),
				'style_property' => 'color'
			),
			$infinity_footer_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'link-color',
				'type' => 'colorpicker',
				'title' => __( 'Link Color', 'infinity-engine' ),
				'description' => __( 'Choose a color for links inside the footer section.', 'infinity-engine' ),
				'style_selector' => 'body.theme-option .footer-wrap a',
				'style_property' => 'color'
			),
			$infinity_footer_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'margin-top',
				'type' => 'css/length-px',
				'title' => __( 'Top Margin', 'infinity-engine' ),
				'description' => __( 'The margin (spacing) between the bottom of the content section and the top of the footer.', 'infinity-engine' ),
				'min' => 0,
				'max' => 100,
				'step' => 2,
				'style_property' => 'margin-top'
			),
			$infinity_footer_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-color',
				'type' => 'css/bg-color',
			),
			$infinity_footer_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-image',
				'type' => 'css/bg-image',
			),
			$infinity_footer_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-repeat',
				'type' => 'css/bg-repeat',
				'parent' => 'background-image',
			),
			$infinity_footer_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'background-repeat',
				'type' => 'css/bg-repeat',
				'parent' => 'background-image',
			),
			$infinity_footer_layout_defaults
		);

		ice_register_option(
			array(
				'name' => 'overlay-image'
			),
			array_merge( $infinity_footer_layout_defaults, $overlay_image_defaults )
		);

		ice_register_option(
			array(
				'name' => 'overlay-opacity',
				'type' => 'css/overlay-opacity',
				'style_selector' => 'body.theme-option .footer-wrap:before',
				'parent' => 'overlay-image',
				'linked_image' => 'overlay-image'
			),
			$infinity_footer_layout_defaults
		);
