<?php
/**
 * Infinity Options Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 *
 * @package Infinity
 * @subpackage config
 */

// See options.examples.php for more advanced configuration examples

//ice_register_option(
//	array(
//		'name' => 'example',
//		'type' => 'text',
//		'section' => 'general',
//		'title' => 'Short description',
//		'description' => 'Long Description',
//		'default_value' => 'Hello World',
//	)
//);

//
// Thumbs group, for post-thumbnails support
//
ice_register_group( 'thumbs' );

	ice_register_option(
		array(
			'name' => 'image-height',
			'group' => 'thumbs',
			'section' => 'global',
			'title' => __( 'Post Thumbnail Height', 'infinity-engine' ),
			'description' => __( 'The height in pixels of the featured images.', 'infinity-engine' ),
			'type' => 'ui/slider',
			'min' => 100,
			'max' => 1500,
			'step' => 10,
			'label' => 'Height in pixels:',
			'default_value' => 240
		)
	);

	ice_register_option(
		array(
			'name' => 'image-width',
			'group' => 'thumbs',
			'section' => 'global',
			'title' => __( 'Post Thumbnail Width', 'infinity-engine' ),
			'description' => __( 'The width in pixels of the featured images.', 'infinity-engine' ),
			'type' => 'ui/slider',
			'min' => 100,
			'max' => 1500,
			'step' => 10,
			'label' => 'Width in pixels:',
			'default_value' => 865
		)
	);
