<?php
/**
 * Infinity Screens Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 *
 * @package Infinity
 * @subpackage config
 */

// register cpanel screen extension
ice_register_extension(
	'screen',
	'cpanel',
	array(
		'path' => INFINITY_ENGINE_PATH . '/extensions/screens/cpanel',
		'class' => 'Infinity_Ext_Screen_Cpanel'
	)
);

ice_register_screen(
	array(
		'name' => 'start',
		'type' => 'cpanel',
		'title' => __( 'Start', 'infinity-engine' ),
		'priority' => 10,
		'template' => 'templates/dashboard/screens/start.php'
	)
);

ice_register_screen(
	array(
		'name' => 'options',
		'type' => 'cpanel',
		'title' => __( 'Options', 'infinity-engine' ),
		'priority' => 20,
		'template' => 'templates/dashboard/screens/options.php'
	)
);
