<?php
/**
 * Infinity Sections Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 *
 * @package Infinity
 * @subpackage config
 */

// register cpanel section extension
ice_register_extension(
	'section',
	'cpanel',
	array(
		'path' => INFINITY_ENGINE_PATH . '/extensions/sections/cpanel',
		'class' => 'Infinity_Ext_Section_Cpanel',
		'template' => 'template.php'
	)
);

ice_register_section(
	array(
		'name' => 'general',
		'type' => 'cpanel',
		'title' => 'General'
	)
);

ice_register_section(
	array(
		'name' => 'global',
		'type' => 'cpanel',
		'title' => 'Global'
	)
);

ice_register_section(
	array(
		'name' => 'custom',
		'type' => 'cpanel',
		'title' => 'Custom'
	)
);

ice_register_section(
	array(
		'name' => 'layout',
		'type' => 'cpanel',
		'title' => 'Layout'
	)
);

ice_register_section(
	array(
		'name' => 'header',
		'type' => 'cpanel',
		'title' => 'Header'
	)
);

ice_register_section(
	array(
		'name' => 'menus',
		'type' => 'cpanel',
		'title' => 'Menus'
	)
);

ice_register_section(
	array(
		'name' => 'menus-top',
		'type' => 'cpanel',
		'parent' => 'menus',
		'title' => 'Above Header'
	)
);

ice_register_section(
	array(
		'name' => 'menus-main',
		'type' => 'cpanel',
		'parent' => 'menus',
		'title' => 'Inside Header'
	)
);

ice_register_section(
	array(
		'name' => 'menus-sub',
		'type' => 'cpanel',
		'parent' => 'menus',
		'title' => 'Below Header'
	)
);

ice_register_section(
	array(
		'name' => 'content',
		'type' => 'cpanel',
		'title' => 'Content'
	)
);

ice_register_section(
	array(
		'name' => 'sidebar',
		'type' => 'cpanel',
		'title' => 'Sidebar'
	)
);

ice_register_section(
	array(
		'name' => 'widgets',
		'type' => 'cpanel',
		'title' => 'Widgets'
	)
);

ice_register_section(
	array(
		'name' => 'footer',
		'type' => 'cpanel',
		'title' => 'Footer'
	)
);

ice_register_section(
	array(
		'name' => 'buddypress',
		'type' => 'cpanel',
		'title' => 'BuddyPress'
	)
);

ice_register_section(
	array(
		'name' => 'whitelabel',
		'type' => 'cpanel',
		'title' => 'White Label'
	)
);

ice_register_section(
	array(
		'name' => 'gravatars',
		'type' => 'cpanel',
		'title' => 'Post Gravatars'
	)
);

// Fall Back

ice_register_section(
	array(
		'name' => 'default',
		'type' => 'cpanel',
		'title' => 'Other'
	)
);
