<?php
/**
 * Infinity Sections Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 *
 * @package Infinity
 * @subpackage config
 */

// register cpanel section extension
ice_register_extension(
	'section',
	'cpanel',
	array(
		'path' => INFINITY_ENGINE_PATH . '/extensions/sections/cpanel',
		'class' => 'Infinity_Ext_Section_Cpanel',
		'template' => 'template.php'
	)
);

ice_register_section(
	array(
		'name' => 'general',
		'type' => 'cpanel',
		'title' => __( 'General', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'global',
		'type' => 'cpanel',
		'title' => __( 'Global', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'custom',
		'type' => 'cpanel',
		'title' => __( 'Custom', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'layout',
		'type' => 'cpanel',
		'title' => __( 'Layout', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'header',
		'type' => 'cpanel',
		'title' => __( 'Header', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'menus',
		'type' => 'cpanel',
		'title' => __( 'Menus', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'menus-top',
		'type' => 'cpanel',
		'parent' => 'menus',
		'title' => __( 'Above Header', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'menus-main',
		'type' => 'cpanel',
		'parent' => 'menus',
		'title' => __( 'Inside Header', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'menus-sub',
		'type' => 'cpanel',
		'parent' => 'menus',
		'title' => __( 'Below Header', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'content',
		'type' => 'cpanel',
		'title' => __( 'Content', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'sidebar',
		'type' => 'cpanel',
		'title' => __( 'Sidebar', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'widgets',
		'type' => 'cpanel',
		'title' => __( 'Widgets', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'footer',
		'type' => 'cpanel',
		'title' => __( 'Footer', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'buddypress',
		'type' => 'cpanel',
		'title' => __( 'BuddyPress', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'whitelabel',
		'type' => 'cpanel',
		'title' => __( 'White Label', 'infinity-engine' )
	)
);

ice_register_section(
	array(
		'name' => 'gravatars',
		'type' => 'cpanel',
		'title' => __( 'Post Gravatars', 'infinity-engine' )
	)
);

// Fall Back

ice_register_section(
	array(
		'name' => 'default',
		'type' => 'cpanel',
		'title' => __( 'Other', 'infinity-engine' )
	)
);
