<?php
/**
 * Infinity Widgets Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 *
 * @package Infinity
 * @subpackage config
 */

ice_register_widget( 
	array(
		'name' => 'pages-list',
		'type' => 'posts-list',
		'title' => 'Edit blog pages',
		'description' => 'Edit your blog pages and modify the order',
		'post_type' => 'page'
	)
);
