<?php
/**
 * Infinity Global Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 *
 * @package Infinity
 * @subpackage config
 */

// The parent theme. Either "infinity", or an ancestor of infinity
$global['parent_theme'] = "";

// Enable/Disable features. This is the same as calling add_theme_support()

$global['feature'] = array(
	// WordPress Setup
	'menus' => true,
	'post-thumbnails' => true,
	'infinity-sidebar-setup' => true,
	'infinity-top-menu-setup' => true,
	'infinity-main-menu-setup' => true,
	'infinity-sub-menu-setup' => true,
	'infinity-footer-menu-setup' => true,
	'infinity-post-thumbnails' => true,
	'infinity-introduction-boxes' => true,
	'infinity-post-avatars' => true,
	'infinity-author-box' => true,
	'infinity-pagination' => true,
	// Core Support
	'infinity-wp-support' => true,
	'infinity-ext-support' => true,
	'infinity-resp-support' => true,
	// Styles
	'infinity-wp-style' => true,
	'infinity-typog-style' => true,
	'infinity-layout-style' => true,
	'infinity-buttons-style' => true,
	'infinity-design-style' => true,
	'infinity-font-iconsweets' => true,
	'infinity-icons-style' => true,
	// Scripts
	'infinity-base-script' => true,
	'infinity-responsive-menu' => true,
	'infinity-responsive-videos' => true,
	// Options Features
	'infinity-core-options' => true,
	'infinity-body-layout' => true,
	'infinity-header-logo' => true,
	'infinity-header-layout' => true,
	'infinity-sidebar-layout' => true,
	'infinity-content-layout' => true,
	'infinity-footer-layout' => true,
	'infinity-main-menu-layout' => true,
	'infinity-widget-layout' => true,
	'infinity-sub-menu-layout' => true,
	'infinity-top-menu-layout' => true,
	'infinity-main-menu-divider' => false,
	'infinity-body-layout' => true,
	'infinity-custom-css' => true,
	// BuddyPress
	'infinity-bp-support' => true,
	'infinity-bp-style' => true,
	'infinity-bp-fbconnect' => true,
	'infinity-bp-sidebar-setup' => true,
	// Other Features
	'infinity-post-gravatar' => false
);

// ------------------------------------------------------------------------------------
// Automatic style enqueuing is handled by the next three sections
// Important: Styles will NEVER be enqueued, UNLESS an action or condition is set
// ------------------------------------------------------------------------------------

// Define your stylesheets
// eg. 'handle' => 'path/to/file.css'
$global['style'] = array(
	'cpanel' => 'dashboard/assets/css/cpanel.css',
	'options' => 'dashboard/assets/css/options.css',
	'docs' => 'dashboard/assets/css/docs.css'
);

// Define dependancies for stylesheets
// These will NOT fail to load if a required handle isn't registered
// eg. 'handle' => array('comma','separated','handles')
$global['style_depends'] = array(
	'cpanel' => array(
		'ice-ui',
		'ice-colorpicker'
	)
);

// Enqueue specific stylesheets ONLY when an action is called
// eg. 'action_name' => array('comma','separated','handles')
$global['style_actions'] = array(
	'admin_print_styles-appearance_page_infinity-theme' => array(
		'cpanel',
		'options',
		'docs'
	)
);

// Enqueue specific stylesheets ONLY if a callback function returns TRUE
// eg. 'function_name' => array('comma','separated','handles')
$global['style_conditions'] = array(
	//'is_front_page' => array( 'google-fonts' ),
	//'is_page:about' => array( 'about-sidebar' )
);

// ------------------------------------------------------------------------------------
// Automatic script enqueuing is handled by the next three sections
// Important: Scripts will NEVER be enqueued, UNLESS an action or condition is set
// ------------------------------------------------------------------------------------

// Define your scripts
// eg. 'handle' => 'path/to/file.js'
$global['script'] = array(
	'superfish' => 'assets/js/superfish.js',
	'cpanel' => 'dashboard/assets/js/cpanel.js',
	'docs' => 'dashboard/assets/js/docs.js'
);

// Define dependancies for scripts
// These will NOT fail to load if a required handle isn't registered
// eg. 'handle' => 'comma,separated,handles'
$global['script_depends'] = array(
	'docs' =>
		array(
			'jquery'
		),
	'cpanel' =>
		array(
			'ice-global',
			'jquery-cookie',
			'jquery-ui-accordion',
			'jquery-ui-position',
			'jquery-ui-sortable',
			'jquery-ui-resizable',
			'jquery-ui-tabs',
			'jquery-juicy-buttonmenu',
			'jquery-juicy-flashmesg',
			'jquery-juicy-toolbar'
		)
);

// Enqueue specific scripts ONLY when an action is called
// eg. 'action_name' => 'comma,separated,handles'
$global['script_actions'] = array(
	'admin_print_scripts-appearance_page_infinity-theme' => array(
		'cpanel',
		'docs'
	)
);

// Enqueue specific scripts ONLY if a callback function returns TRUE
// eg. 'function_name' => 'comma,separated,handles'
$global['script_conditions'] = array(
	//'is_front_page' => array( 'mysliders') ,
	//'is_page:about' => array( 'about-sidebar' ),
	'is_not_admin' => array( 'superfish' )
);

// ===================
//  Advanced Settings
// ===================
$global['advanced'] = array(
	// ---------------------------------------------------------------------
	// Asset files cascading preferences
	// These settings are related to the various asset cascading functions
	// and DO NOT have anything to do with automatic enqueueing.
	// ---------------------------------------------------------------------

	// The root image directory, relative to your theme root
	// If your image directory is: wp-content/themes/my-theme/content/img
	// Then your image root would be: 'image_root' => 'content/img'
	'image_root' => 'assets/images',

	// The root style directory, relative to your theme root
	// If your style directory is: wp-content/themes/my-theme/content/css
	// Then your style root would be: 'style_root' => 'content/css'
	'style_root' => 'assets/css',

	// The root script directory, relative to your theme root
	// If your script directory is: wp-content/themes/my-theme/content/js
	// Then your script root would be: script_root = "content/js"
	'script_root' => 'assets/js',

	// Set the script domain to automatically generate a document.domain expression
	// in the header of every page, including all admin dashboard pages.
	//'script_domain' => 'mydomain.com',

	// ---------------------------------------------------------------------
	// Options panel preferences
	// These settings affect the behavior and display of the options panel
	// ---------------------------------------------------------------------

	// Options panel prefs are under development

	// ---------------------------------------------------------------------
	// jQuery UI preferences
	// These settings affect the initialization and behavior of jQuery UI
	// ---------------------------------------------------------------------

	// Set this to a valid jQuery UI theme stylesheet if you wish to use a
	// theme other than the default which is defined internally
	//'ui_stylesheet' => 'path/to/ui-custom.css',

	// The default is to always show two save buttons.
	// Set this to false if you only want to show the "Save All" button
	'options_save_single' => true,

);

// return config array to caller
return $global;