<?php
/**
 * Infinity Global Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 *
 * @package Infinity
 * @subpackage config
 */

// The parent theme. Either 'infinity', or an ancestor of infinity
$global['parent_theme'] = '';

// Enable/Disable features. This is the same as calling add_theme_support()

$global['feature'] = array(
	// WordPress Setup
	'menus' => true,
	'post-thumbnails' => true,
	'infinity-sidebar-setup' => true,
	'infinity-top-menu-setup' => true,
	'infinity-main-menu-setup' => true,
	'infinity-sub-menu-setup' => true,
	'infinity-footer-menu-setup' => true,
	'infinity-post-thumbnails' => true,
	'infinity-introduction-boxes' => true,
	'infinity-post-avatars' => true,
	'infinity-author-box' => true,
	'infinity-pagination' => true,
	// Core Support
	'infinity-wp-support' => true,
	'infinity-ext-support' => true,
	'infinity-resp-support' => true,
	// Styles
	'infinity-wp-style' => true,
	'infinity-typog-style' => true,
	'infinity-layout-style' => true,
	'infinity-buttons-style' => true,
	'infinity-design-style' => true,
	'infinity-font-iconsweets' => true,
	'infinity-icons-style' => true,
	// Scripts
	'infinity-base-script' => true,
	'infinity-responsive-menu' => true,
	'infinity-responsive-videos' => true,
	// Options Features
	'infinity-core-options' => true,
	'infinity-body-layout' => true,
	'infinity-header-logo' => true,
	'infinity-header-layout' => true,
	'infinity-sidebar-layout' => true,
	'infinity-content-layout' => true,
	'infinity-footer-layout' => true,
	'infinity-main-menu-layout' => true,
	'infinity-widget-layout' => true,
	'infinity-sub-menu-layout' => true,
	'infinity-top-menu-layout' => true,
	'infinity-main-menu-divider' => false,
	'infinity-body-layout' => true,
	'infinity-custom-css' => true,
	// BuddyPress
	'infinity-bp-support' => true,
	'infinity-bp-style' => true,
	'infinity-bp-fbconnect' => true,
	'infinity-bp-sidebar-setup' => true,
	// Other Features
	'infinity-post-gravatar' => false
);

// ===================
//  Advanced Settings
// ===================
$global['advanced'] = array(
	// ---------------------------------------------------------------------
	// Asset files cascading preferences
	// These settings are related to the various asset cascading functions
	// and DO NOT have anything to do with automatic enqueueing.
	// ---------------------------------------------------------------------

	// The root image directory, relative to your theme root
	// If your image directory is: wp-content/themes/my-theme/content/img
	// Then your image root would be: 'image_root' => 'content/img'
	'image_root' => 'assets/images',

	// The root style directory, relative to your theme root
	// If your style directory is: wp-content/themes/my-theme/content/css
	// Then your style root would be: 'style_root' => 'content/css'
	'style_root' => 'assets/css',

	// The root script directory, relative to your theme root
	// If your script directory is: wp-content/themes/my-theme/content/js
	// Then your script root would be: script_root = "content/js"
	'script_root' => 'assets/js',

	// ---------------------------------------------------------------------
	// Options panel preferences
	// These settings affect the behavior and display of the options panel
	// ---------------------------------------------------------------------

	// Options panel prefs are under development

	// ---------------------------------------------------------------------
	// jQuery UI preferences
	// These settings affect the initialization and behavior of jQuery UI
	// ---------------------------------------------------------------------

	// The default is to always show two save buttons.
	// Set this to false if you only want to show the "Save All" button
	'options_save_single' => true,

);

// return config array to caller
return $global;