<?php
/**
 * Infinity Options Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 *
 * @package Infinity
 * @subpackage config
 */

// See options.examples.php for more advanced configuration examples

//ice_register_option(
//	array(
//		'name' => 'example',
//		'type' => 'text',
//		'section' => 'general',
//		'title' => 'Short description',
//		'description' => 'Long Description',
//		'default_value' => 'Hello World',
//	)
//);
