<?php
/**
 * Infinity Options Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 *
 * @package Infinity
 * @subpackage config
 */

$options = array();

// See options.examples.php for more advanced configuration examples

//$options['example'] = array(
//	'type' => 'text',
//	'section' => 'general',
//	'title' => 'Short description',
//	'description' => 'Long Description',
//	'default_value' => 'Hello World',
//);

// return config array to caller
return $options;