<?php
/**
 * Infinity Example Options Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 * 
 * This file is a work in progress.
 *
 * @package Infinity
 * @subpackage config
 */

// We are planning to provide a large number of working example configurations
// which you can copy/paste/tweak into your child theme's options.php

// For the time being, we going to be adding examples for some of the more
// advanced option types until we have more time to write complete docs on them.

// ui/slider with one handle
// this option stores a single number (integer)
$options['slider-one'] =
	array(
		'type' => 'ui/slider',
		'section' => 'general',
		'title' => 'One Handle Slider',
		'description' => 'You can drag the little square around to change the value.',
		'min' => 1,
		'max' => 10,
		'step' => 1,
		'label' => 'You selected:',
		'default_value' => 7
	);

// ui/slider with two handles (range)
// this option stores a two item array, one item for each selected value
$options['slider-two'] =
	array(
		'type' => 'ui/slider',
		'section' => 'general',
		'title' => 'Two Handle Slider',
		'description' => 'You can drag the littles square around to select a range.',
		'min' => 5,
		'max' => 100,
		'step' => 5,
		'range' => 2,
		'label' => 'Your range is:',
		'default_value' => array( 25, 75 )
	);
