<?php
/**
 * Infinity Sections Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 *
 * @package Infinity
 * @subpackage config
 */

$this->register(
	'general',
	array(
		'title' => 'General'
	)
);

$this->register(
	'global',
	array(
		'title' => 'Global'
	)
);

$this->register(
	'custom',
	array(
		'title' => 'Custom'
	)
);

$this->register(
	'layout',
	array(
		'title' => 'Layout'
	)
);

$this->register(
	'header',
	array(
		'title' => 'Header'
	)
);

$this->register(
	'menus',
	array(
		'title' => 'Menus'
	)
);

$this->register(
	'menus-top',
	array(
		'parent' => 'menus',
		'title' => 'Above Header'
	)
);

$this->register(
	'menus-main',
	array(
		'parent' => 'menus',
		'title' => 'Inside Header'
	)
);

$this->register(
	'menus-sub',
	array(
		'parent' => 'menus',
		'title' => 'Below Header'
	)
);

$this->register(
	'content',
	array(
		'title' => 'Content'
	)
);

$this->register(
	'sidebar',
	array(
		'title' => 'Sidebar'
	)
);

$this->register(
	'widgets',
	array(
		'title' => 'Widgets'
	)
);

$this->register(
	'footer',
	array(
		'title' => 'Footer'
	)
);

$this->register(
	'buddypress',
	array(
		'title' => 'BuddyPress'
	)
);

$this->register(
	'whitelabel',
	array(
		'title' => 'White Label'
	)
);

$this->register(
	'gravatars',
	array(
		'title' => 'Post Gravatars'
	)
);

// Fall Back

$this->register(
	'default',
	array(
		'title' => 'Other'
	)
);
