<?php
/**
 * Infinity Sections Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 *
 * @package Infinity
 * @subpackage config
 */

$sections['general'] = array(
	'title' => 'General'
);

$sections['global'] = array(
	'title' => 'Global'
);

$sections['custom'] = array(
	'title' => 'Custom'
);

$sections['layout'] = array(
	'title' => 'Layout'
);

$sections['header'] = array(
	'title' => 'Header'
);

$sections['menus'] = array(
	'title' => 'Menus'
);

$sections['menus-top'] = array(
	'parent' => 'menus',
	'title' => 'Above Header'
);

$sections['menus-main'] = array(
	'parent' => 'menus',
	'title' => 'Inside Header'
);

$sections['menus-sub'] = array(
	'parent' => 'menus',
	'title' => 'Below Header'
);

$sections['content'] = array(
	'title' => 'Content'
);

$sections['sidebar'] = array(
	'title' => 'Sidebar'
);

$sections['widgets'] = array(
	'title' => 'Widgets'
);

$sections['footer'] = array(
	'title' => 'Footer'
);

$sections['buddypress'] = array(
	'title' => 'BuddyPress'
);

$sections['whitelabel'] = array(
	'title' => 'White Label'
);

$sections['gravatars'] = array(
	'title' => 'Post Gravatars'
);

// Fall Back

$sections['default'] = array(
	'title' => 'Other'
);


// return config array to caller
return $sections;