<?php
/**
 * Infinity Shortcodes Configuration.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 * Only edit files in a child theme.
 *
 * @package Infinity
 * @subpackage config
 */

$shortcodes['access'] = array(
	'type' => 'access',
	'title' => 'Access Check',
	'description' => 'Display content to logged in users only',
	'attributes' => array(
		"capability=read"
	)
);

$shortcodes['visitor'] = array(
	'type' => 'visitor',
	'title' => 'Visitor Content',
	'description' => 'Display content to non-logged in users only'
);

// return config array to caller
return $shortcodes;